spring.application.name: shcoolWork
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SchoolWork
    username: root
    password: 123456
mybatis:
  configuration:
   map-underscore-to-camel-case: true








